### ISSUE TITLE
Out of sync with `node-ses`

### ISSUE THREAD

**Issue by markstos** [haoliangyu/node-ses-any-promise#2]
This package is now missing a number of updates since it was forked from `node-ses`. 

https://github.com/aheckmann/node-ses/blob/master/History.md

Meanwhile, as the maintainer of `node-ses` I'd like to switch the API to be promise-based as a breaking change and drop support for the callback-based API. 

Would you be willing to support a pull request to `node-ses` to switch the current code to a promise-based API, essentially merging these works back into one project?

In the the updated docs, we might explain how people can use Bluebird's `asCallback` if they don't want to completely refactor their callback code to use the new version.

A related Github issue about the switch to Promises is here:
https://github.com/aheckmann/node-ses/issues/54

**Comment by markstos** [comment]
Actually, maybe we should both just switch to using the AWS SDK v3 API when it's released. It supports Promises natively, and you no longer have to load the whole giant SDK if you just want to use SES to send an email. Here's what I think example syntax would be like:

```javascript
const {
  SESClient,
  SendEmail
} = require("@aws-sdk/client-ses-node");
async function example() {
  const client = new SESClientt({ region: "us-west-2" });
  const command = new SendEmail({...});
  try {
    const results = await client.send(command);
    console.log(results);
  } catch (err) {
    console.error(err);
  }
}
example();
```

Ref: https://github.com/aws/aws-sdk-js-v3

**Comment by markstos** [comment]
I found the preview of the new SES package on Github. It's here:

https://www.npmjs.com/package/@aws-sdk/client-ses-node

**Comment by haoliangyu** [comment]
@markstos Thank you for mentioning the AWS SDK. This library was developed in the old days when `Promise` was still not native in JavaScript. I don't think this library is necessary any longer. If people want to use `node-ses` with promise, they ca simply promisify the function and it is pretty simple to do.
